name: Verify on PR

on: [pull_request]
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Deps
      run: |
        python -m pip install flake8 pytest
    - name: Run linting
      run: | 
        flake8 src/model/
    - name: Run tests
      run: |
        pytest