name: Main changes

on: 
  push:
    branches:
      - main

# Create two jobs for the github action environments "dev" and "prod" where "prod" depends on "dev"
# and will only run if "dev" passes. This is to ensure that the model is trained in the dev environment
# before being trained in the prod environment.


jobs:
  dev-train:
    name: dev-train
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Train model
      run: az ml job create -f src/job.yml --resource-group mlops-group --workspace-name aml-mlops-dev --stream
  prod-train:
    name: prod-train
    needs: dev-train
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Train model
      run: |
        runid=$(az ml job create -f src/job.yml \
                --set inputs.training_data.path=azureml:diabetes-prod-folder:1 \
                -g mlops-group --workspace-name aml-mlops-dev)
        echo "runid=$runid" >> "$GITHUB_ENV"
    - name: Register model
      run: |
        echo "runid=${{ env.runid }}" 
        az ml model create -n diabetes-model-prod \
          -p runs:/${{ env.runid }}/model --type mlflow_model \
          -g mlops-group --workspace-name aml-mlops-dev 
    - name: Deploy endpoint
      run: az ml online-deployment create -f src/deploy.yml --all-traffic --resource-group mlops-group --workspace-name aml-mlops-dev
    # - name: Test endpoint
    #   run: az ml online-endpoint invoke --name diabetes-endpoint --resource-group mlops-group --workspace-name aml-mlops-dev --request-file tests/datasets/deploy-test.csv 